### ISSUE TITLE
on screen keyboard keeps popping up

### ISSUE THREAD

**Issue by GDM70** [benjamincharity/angular-keypad#11]
Hi,

I'm probably doing something completely wrong but when I use your app the on screen keyboard keeps popping up. I'm using angular 1.6.2.

Please guide me in the right direction.

**Comment by benjamincharity** [comment]
If the native keyboard is appearing, it is likely due to a text input gaining focus. You shouldn't need an input for this; the numbers are just set as a string on the model which you can use as needed.
