### ISSUE TITLE
How to include in Angular 4

### ISSUE THREAD

**Issue by shalomabitan** [benjamincharity/angular-keypad#12]
Hi,

thank you for making this module :)

Do you have an idea of how to include in angular 4? (particularly ionic - but that's not the main concern)

I've tried `import { AngularKeypad } from 'angular-keypad';` but that does not seem to work. I think the biggest issue is the dot in the module name.
```javascript
bc.AngularKeypad (the dot)
```

Any help would be awesome!!! thanks

**Comment by benjamincharity** [comment]
Hey there, unfortunately this was written for AngularJS rather than Angular (this project was named before Angular 2 came out). So in order for it to work with Angular 2+ the library would need to be rewritten. :(

**Comment by shalomabitan** [comment]
Thank you for the quick reply
