### ISSUE TITLE
Init value of keypad input value numbers

### ISSUE THREAD

**Issue by jeanboum** [benjamincharity/angular-keypad#13]
Is it possible to set the value of the input field numbers before launching the keypad? I have an orderlist of several products. I want to change the number of a product by using the keypad.

**Comment by benjamincharity** [comment]
You bet, just set a value on your model in the constructor before passing it into the directive:

```javascript
export class YourController {

    constructor() {
        // Set the initial value here
        this.numbers = '4';
    }

}
```

```html
<bc-keypad bc-number-model="vm.numbers"></bc-keypad>
```
