### ISSUE TITLE
Extra buttons outside keypad

### ISSUE THREAD

**Issue by jeanboum** [benjamincharity/angular-keypad#14]
Is it possible to have some buttons outside the keypad which have effect on the number?
I want to have two buttons (+ / -) to increase / decrease the number by 1.

**Comment by benjamincharity** [comment]
Yep! At the end of the day, this directive simply is adjusting the value of the model you pass in (`vm.numbers` in the docs).

So in the docs example, you would just create your own buttons that change the value of `vm.numbers` when clicked :

```html
<bc-keypad bc-number-model="vm.numbers"></bc-keypad>

<button ng-click="vm.increment(vm.numbers)">Increment</button>
```

```javascript
function increment(value) {
 this.numbers = value + 1;
}
```
