### ISSUE TITLE
C-button in bc-keypad

### ISSUE THREAD

**Issue by jeanboum** [benjamincharity/angular-keypad#15]
In the bc-keypad, I want to add a 'C'-button (to empty the input field number).
Is there a way to do that?
I hope something like: bc-left-button (if necessary combined with bc-left-button-method) and to change the icon with 'C'.

**Comment by benjamincharity** [comment]
Hey @jeanboum you're on the right track..

You can use the left-button and method to do what you want. And you can use the provider to set the template for the button.

- [Docs on using the provider][provider-docs]
- [Docs on using custom method for the left button][methods-docs]
- [Demo using the provider to set the template][provider-demo]
- [Demo using custom methods for the side buttons][methods-demo]


[provider-demo]: https://codepen.io/benjamincharity/pen/YGZGPX
[methods-demo]: https://codepen.io/benjamincharity/pen/VKQjZV
[provider-docs]: https://github.com/benjamincharity/angular-keypad#setbackspacetemplate
[methods-docs]: https://github.com/benjamincharity/angular-keypad#bc-left-button-method
