### ISSUE TITLE
decimal button

### ISSUE THREAD

**Issue by jeanboum** [benjamincharity/angular-keypad#16]
Is there an option to add a 'decimal'-button ?

**Comment by benjamincharity** [comment]
Nothing built in, but you can use the customizable buttons to either side of the `0` button. Check out the docs for [bc-right-button-method](https://github.com/benjamincharity/angular-keypad#bc-right-button-method) for more info. Here is a demo using a custom method: https://codepen.io/benjamincharity/pen/VKQjZV
