### ISSUE TITLE
Dependencies seem to be misconfigured

### ISSUE THREAD

**Issue by zumwald** [benjamincharity/angular-keypad#8]
webpack-dev-server is only for development use, so it should be a dev-dependency rather than a full blown dependency. This is causing npm install errors in CI because we don't want to package webpack-dev-server with our product.

On that note, the readme mentions Angular 1.4.0+ as a dependency, but Angular only included as a dev-dependency at version 1.5.8+.

Cleaning up the dependencies would be much appreciated!

**Comment by benjamincharity** [comment]
Thanks for pointing this out @zumwald! Apparently I was a little too focused on getting 2.0 out and I missed a few housekeeping opportunities.

- [ ] Move `webpack-dev-server` to `devDependencies`.
- [ ] Move AngularJS to `dependencies`.
  - [ ] Add version `^1.4.0` to allow AngularJS from `1.4.0` to any `1.x.x`.

**Comment by benjamincharity** [comment]
Sorted: https://github.com/benjamincharity/angular-keypad/releases/tag/v2.0.1

**Comment by zumwald** [comment]
Thanks @benjamincharity !
